### ISSUE TITLE
Get M3U8 manifest infomation by videojs?

### ISSUE THREAD

**Issue by StriveTeam** [videojs/m3u8-parser#103]
how to get M3U8 manifest infomation by videojs?

**Comment by gkatsev** [comment]
Some of this information is exposed via our VHS project but won't be available when native HLS playback is used. What information are you looking for?

**Comment by chandrakanthd** [comment]
if we need to get the EXT-X-PROGRAM-DATE-TIME tag values, how to access it? I've looked at m3u8 parser, but we need to provide a manifest for it to parse. Is there any API from videojs which provides the manifest data of the feed/each segment? Would really appreciate any help on this.

**Comment by gkatsev** [comment]
date time info is available on the segments object, for example:
```js
player.tech().hls.playlists.media().segments[0].dateTimeString;
player.tech().hls.playlists.media().segments[1].dateTimeObject;
```

**Comment by vanminhquangtri** [comment]
Hi, I want to get this manifest information about the audio. I know I can get the audioTrack for the player but the order of audio is random in Safari after every page reload. So I want to get the audio manifest which is not changed.
