### ISSUE TITLE
help on simple boolean response

### ISSUE THREAD

**Issue by wilburforce83** [videojs/m3u8-parser#104]
Hi, 

I was wondering if there was a simple way to parse an m3u8 using this and to return a simple true/false on whether the m3u8 is working?

Thanks!

**Comment by gkatsev** [comment]
I'm not sure there's an easy way to tell. Just because the m3u8-parser correctly doesn't mean that it works. However, if it doesn't parse, it likely means that it doesn't work.

**Comment by wilburforce83** [comment]
Thanks, pretty much as I thought! I am looking at m3u8stream, if is starts the stream return true, else return false. A bit clunky, but might be the easiest solution!

Thanks for replying so quickly!
