### ISSUE TITLE
Stringify parsed manifest

### ISSUE THREAD

**Issue by easrng** [videojs/m3u8-parser#128]
Is there a way to turn a parsed manifest back into m3u8 format? I need to parse, modify, and then save an m3u8 file and I can't tell how save the manifest back to text format.

**Comment by gkatsev** [comment]
We don't currently provide a way to stringify our JSON output. Unfortunately, we are unable to spend the time adding that functionality.
We've previously reject this ask to keep this project more minimal https://github.com/videojs/m3u8-parser/issues/20#issuecomment-291226195

**Comment by easrng** [comment]
Got it, thanks. Sorry I didn't look at closed issues before I posted this.

**Comment by gkatsev** [comment]
No worries, thanks for asking.
