### ISSUE TITLE
PlayReady DRM

### ISSUE THREAD

**Issue by victordidenko** [videojs/m3u8-parser#142]
Microsoft also made some contribution into HLS format, to support their PlayReady DRM.

See
https://docs.microsoft.com/en-us/playready/packaging/mp4-based-formats-supported-by-playready-clients?tabs=case4

I don't have alive HLS stream with PlayReady to check, and actually I am not sure, how to test playback here, because with the death of old Edge there are no more browsers with PlayReady support on the desktop platform, as far as I know.

But I think minimal change need to be done to avoid issue like #139, filter out `EXT-X-KEY` rows with `KEYFORMAT="com.microsoft.playready"`

**Comment by victordidenko** [comment]
Thanks, @brandonocasey !

**Comment by wjywbs** [comment]
Hi @brandonocasey, could this feature be released to video.js? Thanks
