### ISSUE TITLE
Read tag EXT-OATCLS-SCTE35 in M3U8 manifest information

### ISSUE THREAD

**Issue by vaishalichauhan-ttn** [videojs/m3u8-parser#159]
I want to read the "EXT-OATCLS-SCTE35" tag in M3U8 in an HLS. 

I have tried reading it using player.tech().hls.playlists.media().segments but no luck.

Please help.

**Comment by gkatsev** [comment]
We don't parse non-standard tags by default. You'll want to set up a custom parser https://github.com/videojs/m3u8-parser#custom-parsers
Also see https://github.com/videojs/http-streaming#customtagparsers

**Comment by vaishalichauhan-ttn** [comment]
Thank you. I will try with custom parsers

**Comment by vaishalichauhan-ttn** [comment]
@gkatsev 

const parser = new m3u8Parser.Parser();
parser.addParser({
  expression: /#VOD-TIMING/,
  customType: 'vodTiming',
  segment: true
}

player.src({
  src: 'https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8',
  type: 'application/x-mpegURL',
  customTagParsers: parser
});

Can you please tell me if is this the right way of using custom tags in HLS for getting the tags in " player.tech().hls.playlists.media().segments"?
