### ISSUE TITLE
Get M3U8 String manifest from Object?

### ISSUE THREAD

**Issue by voxsoftware** [videojs/m3u8-parser#23]
How I can make reverse engineer, get m3u8 generated string from Manifest Object? My purpose it's analyze the manifest, delete some items, and regenerate the manifest

**Comment by mjneil** [comment]
This project only supports parsing of manifest files, not generating them from a js object. You would have to write a script that can generate a manifest from the output of the parser if you need to edit the manifest

**Comment by gesinger** [comment]
As @mjneil said, right now we only support parsing. We haven't seen many people ask for this use-case yet (parsing then regenerating), however, it's still a cool idea. If you want to try to write up a generator from the parsed playlist components as a separate module and/or a PR, we'd be happy to take a look. But for now, closing this issue.

**Comment by SamJarmanPP** [comment]
I'd be interested if anyone found a solution to editing m3u8 files in nodejs cc @mjneil

**Comment by weituotian** [comment]
@gesinger it is interesting who can finish this job!!
