### ISSUE TITLE
EXT-X-BYTERANGE parsing incorrect when offset not present

### ISSUE THREAD

**Issue by mjneil** [videojs/m3u8-parser#78]
The `offset` portion of the `EXT-X-BYTERANGE` tag is optional, and should be calculated using the previous segment's offset and bytelength, however the parser currently just assumes a missing offset should default to 0. 

https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.2.2

>If o is not present, the sub-range begins at the next byte following the sub-range of the previous Media Segment.

**Comment by mrlika** [comment]
Hi,
Is it going to be fixed? When is the next release?

**Comment by gesinger** [comment]
A fix is in progress: https://github.com/videojs/m3u8-parser/pull/98

**Comment by jaredstehler** [comment]
PR #98 fixes this issue for me; can we resolve this and publish a new release?

**Comment by AwokeKnowing** [comment]
Is this released?

**Comment by gesinger** [comment]
Sorry for the delay, published as v4.4.3

**Comment by AwokeKnowing** [comment]
@gesinger  Thanks! sorry for my ignorance, we use videojs with eme plugin.   Does this m3u8 parser get bundled into videojs?

**Comment by gesinger** [comment]
We'll have to get the new version into https://github.com/videojs/http-streaming, but we should be doing that soon.
