### ISSUE TITLE
parse title from extinf

### ISSUE THREAD

**Issue by AminTaghikhani** [videojs/m3u8-parser#90]
Hi there,

how can I parse title from the extint?
[reference](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.2.1)

I create 
```js
parser.addParser({
                    expression: /#EXTINF/,
                    customType: 'audio',
                    segment: true,
                    dataParser: function (line) {
                        const valuePart = line.split(':')
                        const values = valuePart[1].split(',')
                        const duration = parseFloat(values[0])
                        const title = values[1]
                        return {
                            duration,
                            title
                        };
                    }
                });
```

but only work for the last item, and the segment doesn't contain anything

**Comment by AminTaghikhani** [comment]
I read your codes, I found [this](https://github.com/videojs/m3u8-parser/blob/07bd668ddb5070fff57f5e5fe86959e18f49c4e3/src/parse-stream.js#L148) line

regex rule is ok, but I think somewhere ignoring ([this](https://github.com/videojs/m3u8-parser/blob/07bd668ddb5070fff57f5e5fe86959e18f49c4e3/src/parse-stream.js#L157))

**Comment by gkatsev** [comment]
Looks like we don't read it and set it out on the output here https://github.com/videojs/m3u8-parser/blob/07bd668ddb5070fff57f5e5fe86959e18f49c4e3/src/parser.js#L106-L131
